version: '3'
services:
  test:
    build: .
    volumes:
      - .:/python
    working_dir: /python
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--auth-host=md5
    command: >
      postgres
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=256MB
      -c work_mem=32MB
      -c max_connections=100
      -c random_page_cost=1.1
      -c temp_buffers=16MB