# Generated by Django 4.2.23 on 2025-07-17 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcomplexmodel',
            name='binary_field',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='testcomplexmodel',
            name='category',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testcomplexmodel',
            name='datetime_field',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcomplexmodel',
            name='integer_field',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcomplexmodel',
            name='json_field',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='testcomplexmodel',
            name='score',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcomplexmodel',
            name='string_field',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcomplexmodel',
            name='test_foreign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_project.testforeignkeymodel'),
        ),
        migrations.AlterField(
            model_name='testuuidmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
